name = "CMake"
grammar = "cmake"
path_suffixes = ["CMakeLists.txt", "cmake"]
line_comments = ["# "]
block_comment = ["#[[", "]]"]
tab_size = 2
hard_tabs = false
autoclose_before = ";:.,=}])> \t\n"

brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
  { start = "${", end = "}", close = true, newline = false },
  { start = "$ENV{", end = "}", close = true, newline = false },
  { start = "$CACHE{", end = "}", close = true, newline = false },
  { start = "$<", end = ">", close = true, newline = false },
]
